### ISSUE TITLE
Error in video of Walk-through: Matrix Multiplication 

### ISSUE THREAD

**Issue by turing4ever** [talkpython/illustrated-python-3-course#1]
In the video of Walk-through: Matrix Multiplication, it defined __mul__ instead of __matmul__ and the test code used v1@v2. According to the pep-0465 and the video prior to this one, operator `@` will call function __matmul__. 

 I am really curious about how the instructor made his code work. It does show exit status code 0 in the video. Maybe a wrong script was called?

**Comment by mikeckennedy** [comment]
Thanks, @mattharrison can you take this one?

**Comment by mattharrison** [comment]
@turing4ever you are correct. I will update the video. Sorry about that

**Comment by mikeckennedy** [comment]
Wonderful. Thanks for recording a new updated video. I just published it to the course. @turing4ever thanks for catching this.
