### ISSUE TITLE
cmath.sqrt() vs **0.5

### ISSUE THREAD

**Issue by turing4ever** [talkpython/illustrated-python-3-course#2]
This is more a question rather than an issue. 
In the video of Walk-through: Keyword-only Arguments, the answer provided is using **0.5 to calculate the square root. If you use cmath.sqrt, you will get solutions that are slightly different and fail the assert. 
So, here is the question: 
1. which way is recommended?
2. How to adjust the assertion so that the rounding error can be ignored correctly and gracefully?

**Comment by mikeckennedy** [comment]
Hi @turing4ever Interesting observation. How about with `import math` rather than cmath?

@mattharrison thoughts?

**Comment by turing4ever** [comment]
import math won't work because of the complex roots.

**Comment by mikeckennedy** [comment]
Ah, got it. Thanks. Matt, want to add a test for both potential solutions?

**Comment by mattharrison** [comment]
@turing4ever Thanks for the report. This should fix it
