### ISSUE TITLE
Async coroutine not awaited

### ISSUE THREAD

**Issue by mikeckennedy** [talkpython/illustrated-python-3-course#4]
Hi @mattharrison This bit of code right here has an issue / warning:

https://github.com/talkpython/illustrated-python-3-course/blob/fdc7ed00098cd4180b4081964bf1bb1dbdee426b/labs/async_test.py#L32

It sends 3 coroutines to be awaited, but with the 2 param it only awaits two causing a warning on exit. Any reason to avoid my changing it to 3?

**Comment by mattharrison** [comment]
I'm not seeing an error with this code:

```
import asyncio
async def add2(x, y):
    res = x + y
    await asyncio.sleep(0)
    return res

async def avg(seq, size):
    items = []
    for item in seq:
        items.append(await item)
        await asyncio.sleep(0)
        items = items[-size:]
        if len(items) == size:
            return sum(items)/size
```

I guess I need more details to reproduce the issue.

**Comment by mikeckennedy** [comment]
Hi @mattharrison The problem is not with either of those two items shown. It's how they are called:

```python
  res3 = await avg([add2(1, 3),
                     add2(1, 4),
                     add2(1, 6),
], 2)
```

See how three calls are there but only 2 are signaled with the last param? That makes the final add not get awaited (`add2(1, 6)`).
